main: me.redraskal.MegaWalls.MegaWalls
name: MegaWalls
version: 1.0
authors: [redraskal, Vanturian]
description: "A perfect copy of Hypixel's Mega Walls gamemode."
load: STARTUP

commands:
  walls:
    description: Main Mega Walls command.